### ISSUE TITLE
8.1 branch is not buildable for cheeseburger

### ISSUE THREAD

**Issue by dkati** [LiquidRemix/android_manifest#2]
i get
hardware/ril-caf/reference-ril/reference-ril.c:40:10: fatal error: 'system/qemu_pipe.h' file not found
#include <system/qemu_pipe.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

any ideas ?

**Comment by dkati** [comment]
You need this ->
https://github.com/LineageOS/android_hardware_ril/commit/ba723cee9906bb0979283e7fdc6af47287cbc42c

into both caf and non-caf ril repo

**Comment by liquid0624** [comment]
should be fixed now
